apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 445412788634.dkr.ecr.us-east-1.amazonaws.com/simplebank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ACCESS_TOKEN_DURATION
              value: "15m"
            - name: REFRESH_TOKEN_DURATION
              value: "24h"
            - name: HTTP_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: GRPC_SERVER_ADDRESS
              value: 0.0.0.0:9090
